"""initial_schema

Revision ID: 82e2e9a75cc1
Revises:
Create Date: 2026-04-24 11:19:31.609117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82e2e9a75cc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogsynclog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets_discovered', sa.Integer(), nullable=False),
    sa.Column('sets_synced', sa.Integer(), nullable=False),
    sa.Column('sets_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customasset_user_id'), 'customasset', ['user_id'], unique=False)
    op.create_table('set',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('release_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('printed_total', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('ptcgo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setsyncstatus',
    sa.Column('set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('cards_count', sa.Integer(), nullable=False),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_table('trade_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_trade_user_card')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=True)
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_wishlist_user_card')
    )
    op.create_table('card',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supertype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtypes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('types', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evolves_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('regulation_mark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('illustrator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ability_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ability_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ability_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack1_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack1_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack1_damage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack1_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack2_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack2_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack2_damage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack2_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack3_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack3_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack3_damage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attack3_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weaknesses', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resistances', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retreat_cost', sa.Integer(), nullable=True),
    sa.Column('rules_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flavor_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('legal_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('legal_expanded', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('legal_unlimited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('national_pokedex_numbers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tcgplayer_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_small', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_large', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number_sort', sa.Integer(), nullable=True),
    sa.Column('set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customassetfield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['customasset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customassetfield_asset_id'), 'customassetfield', ['asset_id'], unique=False)
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strategy_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfoliosnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unrealized_gain', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unrealized_gain_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('unique_cards', sa.Integer(), nullable=False),
    sa.Column('graded_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nm_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lp_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mp_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('played_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('top_card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('top_card_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('top_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('top_set_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfoliosnapshot_snapshot_date'), 'portfoliosnapshot', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_portfoliosnapshot_user_id'), 'portfoliosnapshot', ['user_id'], unique=False)
    op.create_table('showcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showcase_user_id'), 'showcase', ['user_id'], unique=False)
    op.create_table('userportfoliosettings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_snapshot_enabled', sa.Boolean(), nullable=False),
    sa.Column('prefer_manual_prices', sa.Boolean(), nullable=False),
    sa.Column('include_zero_cost_items', sa.Boolean(), nullable=False),
    sa.Column('cost_basis_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('cardfeatures',
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('energy_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('energy_types', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provides_draw', sa.Boolean(), nullable=True),
    sa.Column('provides_search', sa.Boolean(), nullable=True),
    sa.Column('switching', sa.Boolean(), nullable=True),
    sa.Column('gust_effect', sa.Boolean(), nullable=True),
    sa.Column('stadium', sa.Boolean(), nullable=True),
    sa.Column('healing', sa.Boolean(), nullable=True),
    sa.Column('disruption', sa.Boolean(), nullable=True),
    sa.Column('recovery', sa.Boolean(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('deckcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventoryitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_holo', sa.Boolean(), nullable=True),
    sa.Column('is_reverse_holo', sa.Boolean(), nullable=True),
    sa.Column('is_alt_art', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('grading_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('acquired_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchase_price_per_card', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sale_price_per_card', sa.Float(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('sale_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_graded', sa.Boolean(), nullable=False),
    sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manual_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tcgplayer_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ebay_avg_sold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ebay_last_sold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ebay_sale_count', sa.Integer(), nullable=True),
    sa.Column('price_change_7d', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price_change_30d', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('next_refresh', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketprice_card_id'), 'marketprice', ['card_id'], unique=False)
    op.create_index(op.f('ix_marketprice_condition'), 'marketprice', ['condition'], unique=False)
    op.create_table('showcasecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showcase_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['showcase_id'], ['showcase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showcasecard_card_id'), 'showcasecard', ['card_id'], unique=False)
    op.create_index(op.f('ix_showcasecard_showcase_id'), 'showcasecard', ['showcase_id'], unique=False)
    op.create_table('saletransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_proceeds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('realized_gain', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('realized_gain_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listing_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventoryitem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saletransaction_card_id'), 'saletransaction', ['card_id'], unique=False)
    op.create_index(op.f('ix_saletransaction_sale_date'), 'saletransaction', ['sale_date'], unique=False)
    op.create_index(op.f('ix_saletransaction_user_id'), 'saletransaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saletransaction_user_id'), table_name='saletransaction')
    op.drop_index(op.f('ix_saletransaction_sale_date'), table_name='saletransaction')
    op.drop_index(op.f('ix_saletransaction_card_id'), table_name='saletransaction')
    op.drop_table('saletransaction')
    op.drop_index(op.f('ix_showcasecard_showcase_id'), table_name='showcasecard')
    op.drop_index(op.f('ix_showcasecard_card_id'), table_name='showcasecard')
    op.drop_table('showcasecard')
    op.drop_index(op.f('ix_marketprice_condition'), table_name='marketprice')
    op.drop_index(op.f('ix_marketprice_card_id'), table_name='marketprice')
    op.drop_table('marketprice')
    op.drop_table('inventoryitem')
    op.drop_table('deckcard')
    op.drop_table('cardfeatures')
    op.drop_table('userportfoliosettings')
    op.drop_index(op.f('ix_showcase_user_id'), table_name='showcase')
    op.drop_table('showcase')
    op.drop_index(op.f('ix_portfoliosnapshot_user_id'), table_name='portfoliosnapshot')
    op.drop_index(op.f('ix_portfoliosnapshot_snapshot_date'), table_name='portfoliosnapshot')
    op.drop_table('portfoliosnapshot')
    op.drop_table('deck')
    op.drop_index(op.f('ix_customassetfield_asset_id'), table_name='customassetfield')
    op.drop_table('customassetfield')
    op.drop_table('card')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('trade_items')
    op.drop_table('setsyncstatus')
    op.drop_table('set')
    op.drop_index(op.f('ix_customasset_user_id'), table_name='customasset')
    op.drop_table('customasset')
    op.drop_table('catalogsynclog')
    # ### end Alembic commands ###
