#!/usr/bin/env python3
"""Scaffold a new built-in module under services/<id>/.

Generates plugin.yaml, __init__.py, router.py, and models.py — the same
shape as the "Hello module" worked example in docs/MODULE_DEVELOPMENT.md §5
(a per-user setting persisted via plugin_data, zero new tables/migrations),
with requires_core pre-filled to the current core version range. See
docs/RELEASE_PROCESS.md for what requires_core means and when to widen it.

Usage:
    python3 scripts/new_module.py <id> [--name "Display Name"] \\
        [--tier free|premium|core|enterprise] [--api-prefix /<id>]

Example:
    python3 scripts/new_module.py hello --name "Hello Module"

After running, restart the backend — discover_plugins() auto-discovers
services/<id>/plugin.yaml:

    docker compose up -d --no-deps --force-recreate backend

Uses only the stdlib plus app.version (which itself has zero imports), so it
runs on the host without a virtualenv.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from app.version import CORE_VERSION  # noqa: E402

ID_RE = re.compile(r"[a-z][a-z0-9_]*")

PLUGIN_YAML_TEMPLATE = """\
id: {id}
name: {name}
version: 0.1.0
tier: {tier}
type: local
description: TODO — one-line description shown in the Modules UI.
icon: "🔌"
api_prefix: "{api_prefix}"
tags: [{id}]
router_module: services.{id}.router
model_modules: []
requires:
  - auth
requires_core: ">={core_version},<{next_minor}"
"""

ROUTER_PY_TEMPLATE = '''"""
{name} — router.

Generated by scripts/new_module.py. See docs/MODULE_DEVELOPMENT.md for the
settings/secrets patterns (plugin_data, user_secrets) and conventions
(ownership checks, static-before-dynamic routes, commit/refresh, etc.).
"""
from fastapi import APIRouter, Depends
from sqlmodel import Session

from services.shared.database import get_session
from services.auth.middleware import get_current_user
from services.shared.models import User
from services.shared.plugin_data import get_user_plugin_data, set_user_plugin_data

router = APIRouter(prefix="{api_prefix}", tags=["{id}"])

PLUGIN_ID = "{id}"


@router.get("")
def say_hello(current_user: User = Depends(get_current_user)):
    return {{"message": f"Hello, {{current_user.display_name or current_user.email}}!"}}


@router.get("/settings")
def get_settings(
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user),
):
    data = get_user_plugin_data(session, PLUGIN_ID, current_user.id)
    return {{"greeting": data.get("greeting", "Hello")}}


@router.put("/settings")
def update_settings(
    body: dict,
    session: Session = Depends(get_session),
    current_user: User = Depends(get_current_user),
):
    data = set_user_plugin_data(session, PLUGIN_ID, current_user.id, **body)
    return {{"greeting": data.get("greeting", "Hello")}}
'''

MODELS_PY_TEMPLATE = '''"""
{name} — SQLModel tables.

Empty by default — this module persists settings via plugin_data (see
router.py), which needs no tables or migrations. Add SQLModel table classes
here only if you need relational queries/joins; see
docs/MODULE_DEVELOPMENT.md §4(B) for the dedicated-table pattern, and add
this module's dotted path to plugin.yaml's model_modules so
load_plugin_models() imports it before init_db().
"""
'''


def _next_minor(version: str) -> str:
    major, minor, *_ = version.split(".")
    return f"{major}.{int(minor) + 1}.0"


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("id", help="Module id — lowercase snake_case, e.g. 'hello'")
    parser.add_argument("--name", help="Display name shown in the Modules UI (default: title-cased id)")
    parser.add_argument("--tier", default="free", choices=["core", "free", "premium", "enterprise"])
    parser.add_argument("--api-prefix", dest="api_prefix", help="Route prefix, e.g. '/hello' (default: '/<id>')")
    args = parser.parse_args()

    if not ID_RE.fullmatch(args.id):
        raise SystemExit(f"Invalid module id '{args.id}': must be lowercase snake_case (e.g. 'hello', 'my_module')")

    name = args.name or args.id.replace("_", " ").title()
    api_prefix = args.api_prefix if args.api_prefix is not None else f"/{args.id}"

    module_dir = REPO_ROOT / "services" / args.id
    if module_dir.exists():
        raise SystemExit(f"{module_dir} already exists")

    module_dir.mkdir(parents=True)
    (module_dir / "__init__.py").write_text("")
    (module_dir / "plugin.yaml").write_text(PLUGIN_YAML_TEMPLATE.format(
        id=args.id, name=name, tier=args.tier, api_prefix=api_prefix,
        core_version=CORE_VERSION, next_minor=_next_minor(CORE_VERSION),
    ))
    (module_dir / "router.py").write_text(ROUTER_PY_TEMPLATE.format(id=args.id, name=name, api_prefix=api_prefix))
    (module_dir / "models.py").write_text(MODELS_PY_TEMPLATE.format(name=name))

    print(f"Created {module_dir}")
    print()
    print("Next steps:")
    print(f"  - Fill in the description in {module_dir / 'plugin.yaml'}")
    print(f"  - Extend {module_dir / 'router.py'} / models.py")
    print("  - Restart the backend — discover_plugins() auto-discovers services/<id>/plugin.yaml:")
    print("      docker compose up -d --no-deps --force-recreate backend")


if __name__ == "__main__":
    main()
